load(
    "//src/java/com/claro:claro_build_rules_internal.bzl",
    "bootstrapped_claro_module_internal",
    "CLARO_STDLIB_MODULES")

bootstrapped_claro_module_internal(
    name = "sets",
    module_api_file = "sets.claro_module_api",
    srcs = ["sets.claro_internal"],
    visibility = ["//visibility:public"],
)