load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "more_than_syntax_sugar",
    doc_template = "more_than_syntax_sugar.tmpl.md",
    examples = [
        "ex1.claro",
        "ex2.claro",
    ],
)
