load("//:rules.bzl", "claro_module")

claro_module(
    name = "utils",
    module_api_file = "utils.claro_module_api",
    srcs = ["utils.claro"],
    visibility = ["//examples/claro_programs/advent_of_code_2023:__subpackages__"],
)