load("//src/java/com/claro:claro_build_rules_internal.bzl", "bootstrapped_claro_module_internal")

bootstrapped_claro_module_internal(
    name = "lists",
    module_api_file = "lists.claro_module_api",
    srcs = ["lists.claro_internal"],
    visibility = ["//visibility:public"],
)