load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "error_handling",
    doc_template = "error_handling.tmpl.md",
    examples = [
        {
            "example": "ex1.claro",
            "executable": False,
            "append_output": False,
            "codeblock_css_class": "claro",
        },
        "ex2.claro",
        "ex3.claro",
    ],
)
