package(
    default_visibility = [
        "//src/java/com/claro/claro_programs:__subpackages__",
        "//src/java/com/claro/stdlib/claro:__subpackages__",
    ]
)

java_library(
    name = "userinput",
    srcs = glob(["*.java"]),
    deps = [],
)
