load("@claro-lang//:rules.bzl", "claro_binary")

claro_binary(
    name = "part1",
    main_file = "part1.claro",
    resources = {
        "Input": "input.txt",
    },
)

claro_binary(
    name = "part2",
    main_file = "part2.claro",
    resources = {
        "Input": "input.txt",
    }
)
