package(default_visibility = ["//visibility:public"])

load(":claro_build_rules.bzl", "gen_claro_compiler", "DEFAULT_CLARO_NAME")

# Generate the targets for the Claro compiler itself.
gen_claro_compiler()
