load("//src/java/com/claro:claro_build_rules_internal.bzl", "bootstrapped_claro_module_internal")

bootstrapped_claro_module_internal(
    name = "fp",
    module_api_file = "fp.claro_module_api",
    srcs = ["fp.claro"],
    visibility = ["//visibility:public"],
)