load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "swapping_deps",
    doc_template = "swapping_deps.tmpl.md",
    examples = [],
)