load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "var_reassignment",
    doc_template = "var_reassignment.tmpl.md",
    examples = ["ex1.claro"],
)
