load("//src/java/com/claro:claro_build_rules.bzl", "claro_binary")

claro_binary(
    name = "multiple_files",
    main_file = "multiple_files_A.claro",
    srcs = [
        "multiple_files_B.claro",
    ],
)