load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "set_type",
    doc_template = "set_type.tmpl.md",
    examples = [
        "ex1.claro",
        {
            "example": "ex2.claro",
            "executable": False,
            "codeblock_css_class": "claro",
        },
        "ex3.claro",
    ],
)
