load(
    "//src/java/com/claro:claro_build_rules_internal.bzl",
    "bootstrapped_claro_module_internal",
    "CLARO_STDLIB_MODULES")

bootstrapped_claro_module_internal(
    name = "futures",
    module_api_file = "futures.claro_module_api",
    srcs = ["futures.claro_internal"],
    visibility = ["//visibility:public"],
)