load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "visibility",
    doc_template = "visibility.tmpl.md",
    examples = [
        {
            "example": "ex_private_BUILD",
            "executable": False,
            "codeblock_css_class": "python",
        },
        {
            "example": "ex_specific_target_visibility_BUILD",
            "executable": False,
            "codeblock_css_class": "python",
        },
        {
            "example": "ex_package_visibility_BUILD",
            "executable": False,
            "codeblock_css_class": "python",
        },
        {
            "example": "ex_subpackages_visibility_BUILD",
            "executable": False,
            "codeblock_css_class": "python",
        },
        {
            "example": "ex_public_visibility_BUILD",
            "executable": False,
            "codeblock_css_class": "python",
        },
    ],
)
