load("@claro-lang//:rules.bzl", "claro_binary")

# Get the real input at: https://adventofcode.com/2023/day/5

claro_binary(
    name = "part1",
    main_file = "part1.claro",
    resources = {
        "Input": "input.txt",
    },
    deps = {
        "Utils": "//examples/claro_programs/advent_of_code_2023/utils:utils",
    }
)
