package(
    default_visibility = [
        "//visibility:public",
    ]
)

java_library(
    name = "ClaroFuture",
    srcs = glob(["ClaroFuture.java"]),
    deps = [
        "//:guava",
        "//src/java/com/claro/intermediate_representation/types/impls/builtins_impls:builtins_impls",
        "//src/java/com/claro/intermediate_representation/types:type",
        "//src/java/com/claro/intermediate_representation/types",
    ],
)
