load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "map_type",
    doc_template = "map_type.tmpl.md",
    examples = ["ex1.claro"],
)
