load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "if_else",
    doc_template = "if_else.tmpl.md",
    examples = ["ex1.claro"],
)
