
java_library(
    name = "procedure_html",
    srcs = ["ProcedureHtml.java"],
    deps = [
        "//src/java/com/claro/intermediate_representation/types:types",
        "//src/java/com/claro/module_system/module_serialization/proto:serialized_claro_module_java_proto",
        "//src/java/com/claro/module_system/module_serialization/proto/claro_types:claro_types_java_proto",
    ],
    visibility = ["//src/java/com/claro/module_system/clarodocs:__pkg__"],
)