package(
    default_visibility = [
        "//src/java/com/claro/claro_programs:__subpackages__",
        "//src/java/com/claro/compiler_backends/java_source/monomorphization:__subpackages__",
        "//src/java/com/claro/intermediate_representation/types/impls:__subpackages__",
        "//src/java/com/claro/runtime_utilities:__pkg__",
        "//src/java/com/claro/stdlib/claro:__subpackages__",
    ]
)

java_library(
    name = "claro_type_implementation",
    srcs = ["ClaroTypeImplementation.java"],
    deps = [
        "//src/java/com/claro/intermediate_representation/types:type",
    ],
)
