package(
    default_visibility = [
        "//visibility:public",
    ]
)

java_library(
    name = "claro_type_implementation",
    srcs = ["ClaroTypeImplementation.java"],
    deps = [
        "//src/java/com/claro/intermediate_representation/types:type",
    ],
)
