load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "known_bugs",
    doc_template = "known_bugs.tmpl.md",
    examples = [
        "ex1.claro",
        "ex2.claro",
    ],
)
