java_library(
    name = "internal_static_state",
    visibility = ["//src/java/com/claro/intermediate_representation:__subpackages__"],
    srcs = ["InternalStaticStateUtil.java"],
    deps = [
        "//:guava",
        "//src/java/com/claro/intermediate_representation/types:type",
        "//src/java/com/claro/intermediate_representation/types:type_provider",
    ]
)
