load("//src/java/com/claro:claro_build_rules.bzl",
     "claro_library",
     "claro_binary")

claro_binary(
    name = "part1",
    srcs = [":part1_lib"],
    java_name = "part1",
)

claro_library(
    name = "part1_lib",
    src = "part1.claro",
)

claro_binary(
    name = "part2",
    srcs = [":part2_lib"],
    java_name = "part2",
)

claro_library(
    name = "part2_lib",
    src = "part2.claro",
)
