
java_library(
    name = "aliases",
    srcs = ["AliasHtml.java"],
    deps = [
        "//src/java/com/claro/intermediate_representation/types:type",
        "//src/java/com/claro/module_system/clarodocs/html_rendering:util",
        "//src/java/com/claro/module_system/clarodocs/html_rendering/typedefs:type_html",
    ],
    visibility = [
        "//src/java/com/claro/module_system/clarodocs:__pkg__",
    ]
)