load("//:rules.bzl", "claro_module", "claro_binary")
load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "code_reuse",
    doc_template = "code_reuse.tmpl.md",
    examples = [],
)