load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "type_inference",
    doc_template = "type_inference.tmpl.md",
    examples = [
        {
            "example": "ex1.claro",
            "append_output": False,
            "hidden_cleanup": "ex-cleanup.claro",
        },
        {
            "example": "ex2.claro",
            "append_output": False,
            "hidden_cleanup": "ex-cleanup.claro",
        },
    ],
)
