load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "string_formatting",
    doc_template = "string_formatting.tmpl.md",
    examples = ["ex1.claro", "ex2.claro"],
)
