
# TODO(steving) This is only temporary. Long term, once Claro's Module system supports exporting newtype defs and
# TODO(steving)   initializers/unwrappers, then these .claro files should be properly exposed via modules.
exports_files(glob(["*.claro"]))
