java_test(
    name = "CalculatorLexerTest",
    srcs = ["CalculatorLexerTest.java"],
    deps = [
        "//src/java/com/claro/examples/calculator_example:calculator_java_parser",
        "@jflex_rules//third_party/com/google/truth",
        "@jflex_rules//third_party/cup",
    ],
)

java_test(
    name = "CalculatorParserTest",
    srcs = ["CalculatorParserTest.java"],
    deps = [
        "//src/java/com/claro/examples/calculator_example:calculator_java_parser",
        "@jflex_rules//third_party/com/google/truth",
        "@jflex_rules//third_party/cup",
    ],
)
