
java_library(
    name = "sidenav_html",
    srcs = ["SideNavHtml.java"],
    deps = [
        "//:autovalue",
        "//:guava",
    ],
    visibility = ["//src/java/com/claro/module_system/clarodocs/html_rendering/homepage:__pkg__"],
)