load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "struct_type",
    doc_template = "struct_type.tmpl.md",
    examples = ["ex1.claro", "ex2.claro", "ex3.claro"],
)
