load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "pipes",
    doc_template = "pipes.tmpl.md",
    examples = ["ex1.claro", "ex2.claro", "ex3.claro", "ex4.claro"],
)
