
java_library(
    name = "contracts",
    srcs = ["ContractHtml.java"],
    deps = [
        "//:guava",
        "//src/java/com/claro/intermediate_representation/types:types",
        "//src/java/com/claro/module_system/clarodocs/html_rendering:util",
        "//src/java/com/claro/module_system/clarodocs/html_rendering/procedures:procedure_html",
        "//src/java/com/claro/module_system/clarodocs/html_rendering/typedefs:type_html",
        "//src/java/com/claro/module_system/module_serialization/proto:serialized_claro_module_java_proto",
    ],
    visibility = [
        "//src/java/com/claro/module_system/clarodocs:__pkg__",
    ]
)