load("//:rules.bzl", "claro_module", "claro_binary")
load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "reusing_source_code",
    doc_template = "reusing_source_code.tmpl.md",
    examples = [],
)