
java_library(
    name = "homepage_html",
    srcs = ["HomePageHtml.java"],
    deps = [
        "//:guava",
        "//src/java/com/claro/module_system/clarodocs/html_rendering/homepage/sidenav:sidenav_html",
    ],
    visibility = ["//src/java/com/claro/module_system/clarodocs:__pkg__"],
)