load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "default_modules",
    doc_template = "default_modules.tmpl.md",
    examples = [
        "ex1.claro",
        {
            "example": "EX_BUILD",
            "executable": False,
            "codeblock_css_class": "python",
        },
    ],
)
