load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "copying",
    doc_template = "copying.tmpl.md",
    examples = [
        "ex1.claro",
        "ex2.claro",
    ],
)
