load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "not_a_new_type_decl",
    doc_template = "not_a_new_type_decl.tmpl.md",
    examples = [
        "ex1.claro",
    ],
)
