load("//:rules.bzl", "claro_module", "claro_binary")
load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "abstract_modules",
    doc_template = "abstract_modules.tmpl.md",
    examples = [],
)