
java_binary(
    name = "claro_module_deserialization_util",
    main_class = "com.claro.compiler_backends.java_source.deserialization.ClaroModuleDeserializationUtil",
    srcs = ["ClaroModuleDeserializationUtil.java"],
    deps = [
      "//:google-options",
      "//src/java/com/claro/module_system/module_serialization/proto:serialized_claro_module_java_proto",
    ],
    visibility = [
        "//visibility:public",
    ]
)