load("//:rules.bzl", "claro_binary")

claro_binary(
    name = "demo_configurability",
    main_file = "demo_configurability.claro",
    deps = {
        "Messaging": "//examples/claro_programs/modules/demo_configurability/messaging:messaging",
    },
)