package(
    default_visibility = [
        "//visibility:public",
    ]
)


java_library(
    name = "structs",
    srcs = glob(["*.java"]),
    deps = [
        "//src/java/com/claro/intermediate_representation/types:base_type",
        "//src/java/com/claro/intermediate_representation/types:type",
        "//src/java/com/claro/intermediate_representation/types:types",
        "//src/java/com/claro/intermediate_representation/types/impls/builtins_impls:builtins_impls",
    ],
)