load("//src/java/com/claro:claro_build_rules_internal.bzl", "bootstrapped_claro_module_internal")

bootstrapped_claro_module_internal(
    name = "instant",
    module_api_file = "instant.claro_module_api",
    srcs = ["instant.claro_internal"],
    visibility = ["//visibility:public"],
)