load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "sep_var_decl_and_init",
    doc_template = "sep_var_decl_and_init.tmpl.md",
    examples = [
        {
            "example": "ex1.claro",
            "hidden_cleanup": "ex1_cleanup.claro",
            "append_output": False,
        },
    ],
)
