# This is not needed by a typical Bazel project. Only necessary to generate the create_claro_project.sh script with the
# canonical .bazelrc and MODULE.bazel files so that I don't need to maintain two implementations that might diverge.
exports_files([".bazelrc", "MODULE.bazel"])