load("//mdbook_docs:docs_with_validated_examples.bzl", "doc_with_validated_examples")

doc_with_validated_examples(
    name = "consumers",
    doc_template = "consumers.tmpl.md",
    examples = [
        "ex1.claro",
    ],
)
