package(default_visibility = ["//src/java/com/claro/examples/calculator_example/compiler_backends/repl:__pkg__"])

java_library(
    name = "repl_terminal",
    srcs = ["ReplTerminal.java"],
    deps = ["//:lanterna"],
)